### ISSUE TITLE
bug: name not found

### ISSUE THREAD

**Issue by tansaku** [AgileVentures/async_slack_bot#9]
```
{ type: 'message',
  channel: 'D33U268KG',
  user: 'U0292M7AC',
  text: 'vote 3',
  ts: '1480511500.000046',
  team: 'T0285CSTT',
  event: 'direct_message',
  match: [ 'vote', index: 0, input: 'vote 3' ] }
info: ** API CALL: https://slack.com/api/chat.postMessage
info: ** API CALL: https://slack.com/api/chat.postMessage
info: ** API CALL: https://slack.com/api/chat.postMessage
info: ** API CALL: https://slack.com/api/chat.postMessage
start new vote "API - create user"  <https://www.pivotaltracker.com/story/show/134581147>

/home/ubuntu/async_slack_bot/server.js:50
  story.name = match[1]
                    ^
TypeError: Cannot read property '1' of null
    at Object.controller.hears.vote (/home/ubuntu/async_slack_bot/server.js:50:21)
    at Object.<anonymous> (/home/ubuntu/async_slack_bot/node_modules/botkit/lib/CoreBot.js:852:28)
    at Object.Botkit.botkit.trigger (/home/ubuntu/async_slack_bot/node_modules/botkit/lib/CoreBot.js:879:49)
    at Object.<anonymous> (/home/ubuntu/async_slack_bot/node_modules/botkit/lib/SlackBot.js:739:38)
    at Object.Botkit.botkit.trigger (/home/ubuntu/async_slack_bot/node_modules/botkit/lib/CoreBot.js:879:49)
    at /home/ubuntu/async_slack_bot/node_modules/botkit/lib/CoreBot.js:983:32
    at Object.bot.findConversation (/home/ubuntu/async_slack_bot/node_modules/botkit/lib/Slackbot_worker.js:678:9)
    at /home/ubuntu/async_slack_bot/node_modules/botkit/lib/CoreBot.js:979:21
    at next (/home/ubuntu/async_slack_bot/node_modules/botkit/node_modules/ware/lib/index.js:82:27)
    at Ware.run (/home/ubuntu/async_slack_bot/node_modules/botkit/node_modules/ware/lib/index.js:88:3)

```

**Comment by tansaku** [comment]
should be more flexible with spaces ...

**Comment by arreche** [comment]
go to
https://regex101.com/

enter this regular expresion:
`start new vote "(.*)" <?(http.*)>`

And this test string
`start new vote "API - create user"  <https://www.pivotaltracker.com/story/show/134581147>`

This text will not match because it contains two spaces between the story name and URL

**Comment by arreche** [comment]
I would catch this kind of error and respond to user with the right format

**Comment by chaiwa-berian** [comment]
@arreche  can we write the tests for this?

**Comment by arreche** [comment]
@chaiwa-berian We need to solve #7 first to be able to write any tests :)
